apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-frontend
spec:
  selector:
    matchLabels:
      app: inventory-frontend
  template:
    metadata:
      labels:
        app: inventory-frontend
    spec:
      containers:
      - name: frontend
        image: inventory-frontend:latest
        env:
        - name: NEXT_PUBLIC_API_BASE
          value: http://inventory-backend:8000
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-frontend
spec:
  type: NodePort
  selector:
    app: inventory-frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
